# Generated by Django 6.0.7 on 2026-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
