# Generated by Django 6.0.7 on 2026-08-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='brief_description',
            new_name='description',
        ),
    ]
